---
- name: Install git on archlinux
  community.general.pacman:
    name: git
  when: ansible_distribution == "Archlinux"
  become: true

- name: Install git config file
  ansible.builtin.template:
    dest: "{{ home }}/.gitconfig"
    src: gitconfig.j2

- name: Install user gitignore file
  ansible.builtin.copy:
    dest: "{{ home }}/.gitignore"
    src: gitignore
