---
- hosts: local
  connection: local

  pre_tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: default.yml

    - name: Include CLASSE specfic variables
      ansible.builtin.include_vars:
        file: classe.yml
      tags:
        - classe

    - name: Include shared home directory specfic variables
      ansible.builtin.include_vars:
        file: shared-home.yml
      tags:
        - shared-home

  tasks:
    - name: include default module tasks.yaml files
      ansible.builtin.include_tasks:
        file: "{{ module }}/tasks.yaml"
      loop:
        - emacs
        - starship
        - tmux
      loop_control:
        loop_var: module

    - name: include shared home directroy module tasks.yaml files
      ansible.builtin.include_tasks:
        file: "{{ module }}/tasks.yaml"
      loop:
        - i3
      loop_control:
        loop_var: module
      tags:
        - shared-home
