---
- hosts: local
  connection: local

  pre_tasks:
    - name: Include default variables
      ansible.builtin.include_vars:
        file: default.yml

    - name: Include CLASSE specfic variables
      ansible.builtin.include_vars:
        file: classe.yml
      tags:
        - classe

    - name: Include shared home directory specfic variables
      ansible.builtin.include_vars:
        file: shared-home.yml
      tags:
        - shared-home

  tasks:
    - name: include default module tasks.yaml files
      ansible.builtin.include_tasks:
        file: "{{ module }}/tasks.yaml"
      loop:
        - emacs
        - git
        - go
        - nodejs
        - python
        - ssh
        - starship
        - tmux
      loop_control:
        loop_var: module

#    - name: include classe module tasks.yaml files
#      ansible.builtin.include_tasks:
#        file: "{{ module }}/tasks.yaml"
#      loop:
#        -
#      loop_control:
#        loop_var: module
#      tags:
#        - classe

    - name: include shared home directroy module tasks.yaml files
      ansible.builtin.include_tasks:
        file: "{{ module }}/tasks.yaml"
      loop:
        - i3
        - wrappers
      loop_control:
        loop_var: module
      tags:
        - shared-home
