---
- name: Include bash playbook
  ansible.builtin.import_playbook: run.yaml
  vars:
    module: bash

#- hosts: local
#  connection: local
#
#  tasks:
#    - name: Include default variables
#      ansible.builtin.include_vars:
#        file: default.yml
#
#    - name: Include CLASSE specfic variables
#      ansible.builtin.include_vars:
#        file: classe.yml
#      tags:
#        - classe
#
#    - name: Include shared home directory specfic variables
#      ansible.builtin.include_vars:
#        file: shared-home.yml
#      tags:
#        - classe
#
#    - name: Copy other shell setup files from other directories
#      ansible.builtin.copy:
#        src: "{{ item }}"
#        dest: "{{ home }}/.config/bash/{{ item }}"
#      loop:
#        - 00-classe-login.sh
#        - 00-classe-rc.sh
#      tags: classe
