---
- name: Include bash playbook
  ansible.builtin.import_playbook: run.yaml
  vars:
    module: bash

- name: Add login files from other modules
  hosts: local
  connection: local

  tasks:
    - name: Copy other shell setup files from other directories
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ home }}/.config/bash/{{ item | basename }}"
      loop:
        - python/10-python-login.sh
