---
- name: Download latest starship from GitHub
  ansible.builtin.unarchive:
    src: "{{
      lookup('url',
             'https://api.github.com/repos/starship/starship/releases/latest',
             split_lines = false)
      | regex_search('browser_download_url.*(https://(.*?).tar.gz)', '\\1')
      | first
    }}"
    dest: "{{ dot_local }}/bin"
    remote_src: true

- name: Copy starship config file
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ home }}/.config/starship.toml"
