---
- name: Check pkcsrc symlinks for i3 and supporting binaries
  ansible.builtin.file:
    path: "{{ dot_local }}/bin/{{ item }}"
    src: "{{ pkgsrc_dir }}/bin/{{ item }}"
    state: link
  loop:
    - i3
    - i3-config-wizard
    - i3-dmenu-desktop
    - i3-dump-log
    - i3-input
    - i3-migrate-config-to-v4
    - i3-msg
    - i3-nagbar
    - i3-save-tree
    - i3-sensible-editor
    - i3-sensible-pager
    - i3-sensible-terminal
    - i3-with-shmlog
    - i3bar
    - feh
    - picom
    - picom-trans
    - xss-lock
  when: ansible_facts['os_family'] == "RedHat"

- name: Check custom dmenu symlinks
  ansible.builtin.file:
    path: "{{ dot_local }}/bin/{{ item }}"
    src: "{{ home }}/Programs/dmenu/bin/{{ item }}"
    state: link
  loop:
    - dmenu
    - dmenu_path
    - dmenu_run

- name: Check dunst symlinks
  ansible.builtin.file:
    path: "{{ dot_local }}/bin/{{ item }}"
    src: "{{
      (distro == 'el7')
        | ternary(home + '/Programs/dunst-1.5.0/bin/' + item,
                  chess_dir + '/Pkgsrc/' + distro + '/bin/' + item)
    }}"
    state: link
  loop:
    - dunst
    - dunstctl

- name: Get dex autostart program
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jceb/dex/master/dex
    dest: "{{ dot_local }}/bin/dex"
    mode: "0755"


- name: Create ~/.config directories
  ansible.builtin.file:
    path: "{{ home }}/.config/{{ item }}"
    state: directory
  loop:
    - autostart
    - dunst
    - i3

- name: Copy i3 config file
  ansible.builtin.copy:
    dest: "{{ home }}/.config/i3/config"
    src: config

- name: Copy wallpaper directory
  ansible.builtin.copy:
    dest: "{{ home }}/.config/i3/"
    src: wallpaper

- name: Disable some system autostarted programs
  ansible.builtin.copy:
    dest: "{{ home }}/.config/autostart/{{ item }}"
    src: hidden.desktop
  loop:
    - org.gnome.Evolution-alarm-notify.desktop
    - print-applet.desktop
    - sealertauto.desktop
    - vmware-user.desktop
    - xfce4-power-manager.desktop

- name: Copy dunst config files
  ansible.builtin.copy:
    dest: "{{ home }}/.config/dunst/dunstrc"
    src: dunstrc
