---
- name: Check/Install tmux on archlinux
  community.general.pacman:
    name: tmux
  when: ansible_distribution == "Archlinux"
  become: true

- name: Check tmux symlink
  ansible.builtin.file:
    src: "{{ pkgsrc_dir }}/bin/tmux"
    dest: "{{ dot_local }}/bin/tmux"
    state: link
  when: ansible_facts['os_family'] == "RedHat"


- name: Copy tmux config file
  ansible.builtin.copy:
    src: tmux.conf
    dest: "{{ home }}/.tmux.conf"
