---
- name: Ensure needed packages are installed
  become: True
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
    - ghostty
    - python-pipx
    - starship
    - stow
    - tmux
    - uv

